/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountChain: typeof import('./../components/AccountChain/index.vue')['default']
    BackTo: typeof import('./../components/BackTo/index.vue')['default']
    Column: typeof import('./../components/TitanTable/src/Column.vue')['default']
    CommonBalanceInfo: typeof import('./../components/CommonBalanceInfo/index.vue')['default']
    CommonTransferTable: typeof import('./../components/CommonTransferTable/index.vue')['default']
    CommonTxTable: typeof import('./../components/CommonTxTable/index.vue')['default']
    CopyIt: typeof import('./../components/CopyIt/index.vue')['default']
    CopyMe: typeof import('./../components/CopyMe/index.vue')['default']
    CustomTabs: typeof import('./../components/CustomTabs/index.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FeatureList: typeof import('./../components/FeatureList/index.vue')['default']
    Form: typeof import('./../components/TitanForm/src/Form.vue')['default']
    FormItem: typeof import('./../components/TitanForm/src/FormItem.vue')['default']
    FormRender: typeof import('./../components/TitanForm/src/FormRender.vue')['default']
    Hamburger: typeof import('./../components/Hamburger/index.vue')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    MyCard: typeof import('./../components/MyCard/index.vue')['default']
    MyChart: typeof import('./../components/MyChart/index.vue')['default']
    NumberShow: typeof import('./../components/NumberShow/index.vue')['default']
    Pagination: typeof import('./../components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchHash: typeof import('./../components/SearchHash/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    Table: typeof import('./../components/TitanTable/src/Table.vue')['default']
    TargetsWrapper: typeof import('./../components/TargetsWrapper/index.vue')['default']
    TimeAgo: typeof import('./../components/TimeAgo/index.vue')['default']
    TransitionList: typeof import('./../components/TransitionList/index.vue')['default']
    TransitionTable: typeof import('./../components/TransitionTable/index.vue')['default']
    TrendNum: typeof import('./../components/TrendNum/index.vue')['default']
    TxDetail: typeof import('./../components/TxDetail/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
